postgresql_user: "supertokens_user"
postgresql_password: "password"
postgresql_host: "192.168.1.3"
postgresql_port: 5432
postgresql_database_name: "treasury"
core_config_version: 0
host: "0.0.0.0"
postgresql_config_version: 0
info_log_path: null
error_log_path: null
