export enum EmailTemplates {
    VerifyEmailTemplate = 'verifyEmailTemplate',
    ResetPasswordTemplate = 'resetPasswordTemplate',
    NewIdeaCommentTemplate = 'newIdeaCommentTemplate',
    NewProposalCommentTemplate = 'newProposalCommentTemplate',
    NewBountyCommentTemplate = 'newBountyCommentTemplate',
    NewChildBountyCommentTemplate = 'newChildBountyCommentTemplate',
    NewTipCommentTemplate = 'newTipCommentTemplate',
    TestTemplate = 'testTemplate',
    TaggedInIdeaCommentTemplate = 'taggedInIdeaCommentTemplate',
    TaggedInProposalCommentTemplate = 'taggedInProposalCommentTemplate',
    TaggedInBountyCommentTemplate = 'taggedInBountyCommentTemplate',
    TaggedInChildBountyCommentTemplate = 'taggedInChildBountyCommentTemplate',
    TaggedInTipCommentTemplate = 'taggedInTipCommentTemplate',
}
