version: '3'
services:
  backend-test-ci:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    environment:
      DEPLOY_ENV: test
      TEAMCITY_VERSION: ${TEAMCITY_VERSION}
    command: bash -c "while !</dev/tcp/database/5432; do sleep 1; done; npm run database:migrate:ci && npm run test:ci"
    depends_on:
      - database
      - substrate
  database:
    build:
      context: ./database
    volumes:
      - ${PROJECT_DIR:-../}/deploy/pg-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres; do sleep 1; done
    restart: unless-stopped
  substrate:
    image: parity/polkadot:v0.8.24
    ports:
      - "9944:9944"
    command: --rpc-external --ws-external --dev
    restart: unless-stopped
