version: '3'
services:
    backend:
        build:
            context: ../
            dockerfile: backend/Dockerfile
            args:
                REACT_APP_DEPLOY_ENV: development
        ports:
            - '3001:3001'
        environment:
            DEPLOY_ENV: 'development-docker'
        command: bash -c "while !</dev/tcp/database/5432; do sleep 1; done; DATABASE_USERNAME=deployer npm run database:migrate && npm run main:dist"
        depends_on:
            - database
            - local-development-polkadot-1
            - local-development-polkadot-2
            - authorization
    database:
        build:
            context: ./database
        ports:
            - '5432:5432'
        volumes:
            - ${PROJECT_DIR:-../}/deploy/pg-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres; do sleep 1; done
        restart: unless-stopped
    local-development-polkadot-1:
        container_name: local-development-polkadot-1
        build:
            context: ./
            dockerfile: polkadot.Dockerfile
        ports:
            - '9944:9944'
        command: --rpc-external --ws-external --dev
        volumes:
            - ${PROJECT_DIR:-../}/deploy/local-development-polkadot-1-data:/polkadot
        restart: unless-stopped
    local-development-polkadot-2:
        container_name: local-development-polkadot-2
        build:
            context: ./
            dockerfile: polkadot.Dockerfile
        ports:
            - '9955:9944'
        command: --rpc-external --ws-external --dev
        volumes:
            - ${PROJECT_DIR:-../}/deploy/local-development-polkadot-2-data:/polkadot
        restart: unless-stopped
    authorization:
        ports:
            - '3567:3567'
        image: supertokens/supertokens-postgresql:3.7
        depends_on:
            - database
        environment:
            - POSTGRESQL_USER=authorization_manager
            - POSTGRESQL_PASSWORD=password
            - POSTGRESQL_HOST=database
            - POSTGRESQL_PORT=5432
            - POSTGRESQL_DATABASE_NAME=treasury_authorization
        restart: unless-stopped
