export const ROUTE_ROOT = '/'
export const ROUTE_IDEAS = '/ideas'
export const ROUTE_NEW_IDEA = '/ideas/new'
export const ROUTE_EDIT_IDEA = '/ideas/edit/:ideaId'
export const ROUTE_IDEA = '/ideas/:ideaId/:contentType?'
export const ROUTE_PROPOSALS = '/proposals'
